Get apis of Applicants and Jobs
Gemini-Solutions/ATS_API_Automation pull request #1
Opened 2023-03-29 09:24 UTC by gem-charugarg

2023-03-30 12:22 UTC, gem-aryanpurru reviewed
1. Add logger info in catch block
2. Add proper comments before function definition
3. Follow correct camel casing while naming function. 
4. If condition for ((response.getResponseBody()) != null) must be added to line 75 (utils file) to avoid, redundant code.
5. Feature file contains multiple redundant code
6. Remove all the redundant comments with code.

2023-04-03 07:11 UTC, gem-pawandeep requested changes
1. change stepdefinition to stepDefinition.
2. remove unwanted variables.
3. remove dead code.
4. use ^ $ in   @Given("Set the Applicant endpoint {string} and method {string}").
5. use appropriate language for scenario name, ex : ATS, Healthcheck for Applicants API.
6. use proper camel casing in method an variables name

2023-04-03 08:00 UTC, gem-charugarg commented
> 1. change stepdefinition to stepDefinition.
> 2. remove unwanted variables.
> 3. remove dead code.
> 4. use ^ $ in   @given("Set the Applicant endpoint {string} and method {string}").
> 5. use appropriate language for scenario name, ex : ATS, Healthcheck for Applicants API.
> 6. use proper camel casing in method an variables name
 

HI @gem-pawandeep, I will make changes accordingly. but there are few points to consider from my end as well.
As per the 1st point, I named package as per accepted industry standard (Attaching the reference link below)
[Oracle package naming conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)
Also for 2nd ,3rd and 6th points you might have not reviewed the latest commit, it might be the previous commit.
And as per the remaining points I will make changes and will update you soon.
Thanks.

2023-04-03 08:33 UTC, gem-pawandeep commented on src/main/java/com/qa/ats/stepdefinition/ApplicantStep.java
> +            GemTestReporter.addTestStep("Hit API", "User not able to hit the API", STATUS.PASS);
I think this line shouldn't be there. GemTestReporter.addTestStep("Hit API", "User not able to hit the API", STATUS.PASS)

2023-04-03 08:35 UTC, gem-pawandeep commented on src/main/java/com/qa/ats/stepdefinition/JobsStep.java
> +            GemTestReporter.addTestStep("Status Check", "Verify the API status", STATUS.PASS);
if you are verifying the status code through verifyStatusCode method then GemTestReporter.addTestStep("Status Check", "Verify the API status", STATUS.PASS); shouldn't be there

2023-04-03 08:38 UTC, gem-pawandeep commented on src/main/java/com/qa/ats/utils/Utils.java
>              GemTestReporter.addTestStep("Response Message", response.getResponseMessage(), STATUS.INFO);
please combine or change these 2 steps and use logger here,

2023-04-03 10:50 UTC, gem-pawandeep approved these changes

2023-04-03 10:56 UTC, gem-pawandeep approved these changes
approved!!!

2023-04-03 10:59 UTC, merged